name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # or whatever branch you want to track

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git LFS (Large File Storage) - If needed
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Install Hugging Face CLI
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub

    - name: Hugging Face CLI login
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Force push repository to Hugging Face Space
      run: |
        git push --force https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/team03-capstone main
